name: "[manual] - Data Scrape by Population"

on:
  workflow_dispatch:
    inputs:
      state:
        description: "State initials (e.g. co, wa)"
        required: true
        type: choice
        options:
          - co
          - wa
      num_jurisdictions:
        description: "Number of jurisdictions to scrape by population (e.g. 10 for top 10)"
        required: false
        default: 10
        type: number

jobs:
  fetch-jurisdictions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Pull docker image
        run: |
          docker compose -f docker-compose.github-actions.yml pull civicpatch-cicd

      - name: Fetch jurisdictions
        id: find-jurisdictions
        env:
          CRUDDER_SHARED_TOKEN: ${{ secrets.CRUDDER_SHARED_TOKEN }}
          CRUDDER_URL: https://crudder.civicpatch.org
        run: |
          # Create a temporary file to store the jurisdictions
          TMP_FILE="$RUNNER_TEMP/jurisdictions.json"

          # Run the CLI command and save the output to the temporary file
          curl -s -X GET "${CRUDDER_URL}/api/jurisdictions/available?num_jurisdictions=${{ github.event.inputs.num_jurisdictions }}&state=${{ github.event.inputs.state }}" \
            -H "Authorization: ${CRUDDER_SHARED_TOKEN}" > $TMP_FILE

          # Use jq to extract the jurisdictions and format them as a JSON array for the matrix
          jq -c '.jurisdictions[] | {id, name, url}' "$TMP_FILE" > "$RUNNER_TEMP/matrix.json"

      - name: Set matrix
        id: set-matrix
        run: |
          # Convert the JSON array into a GitHub Actions matrix format
          echo "matrix=$(jq -c -s '.' $RUNNER_TEMP/matrix.json)" >> $GITHUB_OUTPUT

  run-pipelines:
    needs: fetch-jurisdictions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jurisdiction: ${{ fromJson(needs.fetch-jurisdictions.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Pull docker image
        run: |
          docker compose -f docker-compose.github-actions.yml pull civicpatch-cicd

      - name: Run data scrape
        env:
          BRAVE_SEARCH_TOKEN: ${{ secrets.BRAVE_SEARCH_TOKEN }}
          GOOGLE_SEARCH_TOKEN: ${{ secrets.GOOGLE_SEARCH_TOKEN }}
          GOOGLE_SEARCH_ENGINE_ID: ${{ secrets.GOOGLE_SEARCH_ENGINE_ID }}
          SERP_API_TOKEN: ${{ secrets.SERP_API_TOKEN }}

          GOOGLE_GEMINI_TOKEN: ${{ secrets.GOOGLE_GEMINI_TOKEN }}
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
          TOGETHER_AI_TOKEN: ${{ secrets.TOGETHER_AI_TOKEN }}

          CRUDDER_SHARED_TOKEN: ${{ secrets.CRUDDER_SHARED_TOKEN }}
          CRUDDER_URL: https://crudder.civicpatch.org 
        run: |
          echo "Running pipeline for jurisdiction: ${{ matrix.jurisdiction.name }}"
          docker compose -f docker-compose.github-actions.yml run --rm civicpatch-cicd poetry run \
            python src/cli/cli.py \
              run_pipeline \
                --jurisdiction-id "${{ matrix.jurisdiction.id }}" \
                --name "${{ matrix.jurisdiction.name }}" \
                --url "${{ matrix.jurisdiction.url }}"

